#!/bin/bash

set -e
apt-get install -yq python-pip
pip install -r hooks/requirements.txt
mkdir -p /etc/ansible/facts.d

$ cat <<EOF > /etc/ansible/facts.d/swarm.fact
[command]
join=
manage=
[state]
reload=
EOF
