#!/bin/bash

set -e
easy_install pip
apt-get install -y socat
pip install -r hooks/requirements.txt
mkdir -p /etc/ansible/facts.d

[ -s /etc/ansible/facts.d/swarm.fact ] \
    && cat <<EOF > /etc/ansible/facts.d/docker.fact
[swarm]
join=
manage=
[state]
reload=
EOF
